/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'holy-bg': 'var(--bg)',
        'holy-surface': 'var(--surface)',
        'holy-surface2': 'var(--surface2)',
        'holy-primary': 'var(--primary)',
        'holy-primary-text': 'var(--primary-text)',
        'holy-text': 'var(--text)',
        'holy-text-secondary': 'var(--text-secondary)',
      },
      fontFamily: {
        sans: ['var(--font-family)'],
        mono: ['var(--font-mono)'],
        anton: ['Anton', 'sans-serif'],
        'jetbrains': ['JetBrains Mono', 'monospace'],
        cinzel: ['Cinzel', 'serif'],
        audiowide: ['Audiowide', 'display'],
        bungee: ['Bungee', 'display'],
        'special-elite': ['Special Elite', 'display'],
        'press-start': ['Press Start 2P', 'display'],
        'playfair': ['Playfair Display', 'serif'],
        'black-ops': ['Black Ops One', 'display'],
        caveat: ['Caveat', 'cursive'],
        lobster: ['Lobster', 'cursive'],
        'unifrakur': ['UnifrakturCook', 'display'],
        'old-standard': ['Old Standard TT', 'serif'],
        'permanent-marker': ['Permanent Marker', 'cursive'],
        orbitron: ['Orbitron', 'sans-serif'],
        'yuji-mai': ['Yuji Mai', 'serif'],
        megim: ['Megrim', 'display'],
        'russo-one': ['Russo One', 'sans-serif'],
        'cormorant-sc': ['Cormorant SC', 'serif'],
        'faster-one': ['Faster One', 'display'],
        'architects': ['Architects Daughter', 'cursive'],
        'allerta-stencil': ['Allerta Stencil', 'sans-serif'],
        italianno: ['Italianno', 'cursive'],
        'rubik-mono': ['Rubik Mono One', 'sans-serif'],
        monoton: ['Monoton', 'display'],
        'pirata-one': ['Pirata One', 'display'],
        bebas: ['Bebas Neue', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
